#ifndef __CORAL_CONFIG_H
#define __CORAL_CONFIG_H

#define CORAL_PACKAGE "coral"
#define CORAL_VERSION "0.55.0"

#define CORAL_HAVE_BOOST
#define CORAL_HAVE_BOOST_CONTEXT
#define CORAL_HAVE_BOOST_FILESYSTEM
#define CORAL_HAVE_BOOST_PROGRAM_OPTIONS
#define CORAL_HAVE_BOOST_REGEX
#define CORAL_HAVE_BOOST_SYSTEM
#define CORAL_HAVE_BOOST_THREAD

#define CORAL_HAVE_LIBDOUBLE_CONVERSION 1
#define CORAL_HAVE_LIBGFLAGS 1
#define CORAL_HAVE_LIBGLOG 1
#define CORAL_HAVE_LIBGTEST 1

#define CORAL_HAVE_LIBJEMALLOC 1
#define CORAL_HAVE_LIBEVENT 1
#define CORAL_HAVE_LIBLZ4 1
#define CORAL_HAVE_LIBLZMA 1
#define CORAL_HAVE_LIBSNAPPY 1
#define CORAL_HAVE_LIBSSL 1
#define CORAL_HAVE_LIBZ 1

#define CORAL_HAVE_BYTESWAP_H 1
#define CORAL_HAVE_DLFCN_H 1
#define CORAL_HAVE_EMMINTRIN_H 1
#define CORAL_HAVE_FCNTL_H 1
#define CORAL_HAVE_FEATURES_H 1
#define CORAL_HAVE_INTTYPES_H 1
#define CORAL_HAVE_LIMITS_H 1
#define CORAL_HAVE_MALLOC_H 1
#define CORAL_HAVE_MEMORY_H 1
/* #undef CORAL_HAVE_MUTEX_H */
#define CORAL_HAVE_STDBOOL_H 1
#define CORAL_HAVE_STDINT_H 1
#define CORAL_HAVE_STDLIB_H 1
#define CORAL_HAVE_STRING_H 1
#define CORAL_HAVE_STRINGS_H 1
#define CORAL_HAVE_UNISTD_H 1
#define CORAL_HAVE_BITS_C__CONFIG_H 1
#define CORAL_HAVE_BITS_FUNCTEXCEPT_H 1
#define CORAL_HAVE_SYS_STAT_H 1
#define CORAL_HAVE_SYS_TIME_H 1
#define CORAL_HAVE_SYS_TYPES_H 1

#define CORAL_HAVE_INT128_T 1
#define CORAL_HAVE_PTHREAD_SPINLOCK_T 1
#define CORAL_HAVE_PTRDIFF_T 1

#define CORAL_HAVE_GETDELIM 1
#define CORAL_HAVE_GETTIMEOFDAY 1
/* #undef CORAL_HAVE_MALLOC_SIZE */
#define CORAL_HAVE_MALLOC_USABLE_SIZE 1
#define CORAL_HAVE_MEMMOVE 1
#define CORAL_HAVE_MEMRCHR 1
#define CORAL_HAVE_MEMSET 1
#define CORAL_HAVE_PIPE2 1
#define CORAL_HAVE_STRERROR 1

#define CORAL_HAVE_CPLUS_DEMANGLE_V3_CALLBACK 1
#define CORAL_HAVE_POW 1
#define CORAL_HAVE_PTHREAD_ATFORK 1
#define CORAL_HAVE_PTHREAD_YIELD 1
#define CORAL_HAVE_CLOCK_GETTIME 1

/* #undef CORAL_HAVE_SCHED_H */
/* #undef CORAL_HAVE_SCHED_YIELD */

#define CORAL_FINAL final
#define CORAL_OVERRIDE override

/* #undef CORAL_USE_LIBCPP */

#define CORAL_HAVE_CONSTEXPR_STRLEN 1
#define CORAL_HAVE_IFUNC 1
#define CORAL_HAVE_STD__THIS_THREAD__SLEEP_FOR 1
/* #undef CORAL_HAVE_STD__IS_TRIVIALLY_COPYABLE */
/* #undef CORAL_HAVE_VSNPRINTF_ERRORS */
#define CORAL_HAVE_WEAK_SYMBOLS 1
/* #undef CORAL_HAVE_XSI_STRERROR_R */

#define CORAL_GFLAGS_NAMESPACE google
#define CORAL_UNUSUAL_GFLAGS_NAMESPACE 1

#endif /* __CORAL_CONFIG_H */

